export const WALLET_CONNECT = 'WALLET_CONNECT'
export const WALLET_GET_ACCOUNT = 'WALLET_GET_ACCOUNT'
export const WALLET_SIGN_MESSAGE = 'WALLET_SIGN_MESSAGE'
export const WALLET_DISCONNECT = 'WALLET_DISCONNECT'